[package]
name = "http-sig"
version = "0.1.0"
authors = ["Jack Cargill <jack@passfort.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
hmac = "0.7.1"
http = "0.2.0"
sha2 = "0.8.1"
base64 = "0.11.0"
reqwest = {version = "0.10.1", features = ["blocking"], optional = true}
